### ISSUE TITLE
Implement generic User table

### ISSUE THREAD

**Issue by StephenStrickland** [theNerd247/breeze-check#48]
This table should allow developers to quickly generate a standardized view for Persons.
This table should have the following functionality.
- [ ] Check box, with settable highlight color
- [ ] Trashcan icon for removing a user from a set
- [ ] Edit icon for editing the row?
- [ ] ...

**Comment by theNerd247** [comment]
I've fixed this with 2bdd89e248e05d92ebc8e911e521dbfd95b806cb

To provide the ability to control whether to display checkboxes and highlight a row when selected and for modifying the underlying data using forms I created the `Person` module to contain all MVUs directly related to a `Person`. Also, I switched the data type for storing a list of people to a `Dict Person` (aliased as `Persons` in the `Person` module...this made it much easier to perform updates and provide a safe universal way to handling messages passed to the update function in the `Person` module.

Also, I finally found a version of `elm-export` so I've gone ahead and fixed all the JSON handling to and from the server. So the `Data` module is now auto generated. I removed the `Has...` aliases that were in `Data` because they were on such a microscale that it wasn't necessary (nothing broke by doing this)
